System:
  name: my_new_app           
  repository: # link to the repository where the components are located    # optional
  input_media: # local path to the input media file to be processed
  components: ['component-name-1', 'component-name-2', ...]                # does not have to be in order
  dependencies: [['component-name-1', 'component-name-2', 1], ...] 
