# Define parent image, alpine for efficiency
FROM python:3.8-bullseye

WORKDIR /usr/src/app

# Install system packages
COPY requirements.sys ./
RUN apt-get update && xargs -a requirements.sys apt-get install -y

# Install python packages
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Set up the directory structure as used in the components
RUN mkdir -p /usr/src/app/aisprint/onnx_inference \
    && mkdir -p /usr/src/app/aisprint/annotations \
    && mkdir -p /usr/src/app/aisprint/monitoring

# Install AI-SPRINT annotation and load_and_inference packages
RUN apt-get update && apt-get install -y wget \
    && wget -O /usr/src/app/aisprint/onnx_inference/onnx_inference.py https://gitlab.polimi.it/ai-sprint/ai-sprint-studio/-/raw/master/src/aisprint/onnx_inference/onnx_inference.py \
    && wget -O /usr/src/app/aisprint/annotations/annotations.py https://gitlab.polimi.it/ai-sprint/ai-sprint-studio/-/raw/master/src/aisprint/annotations/annotations.py \
    && wget -O /usr/src/app/aisprint/monitoring/monitoring.py https://gitlab.polimi.it/ai-sprint/ai-sprint-studio/-/raw/master/src/aisprint/monitoring/monitoring.py

# Ensure clean state
RUN apt-get purge -y --auto-remove wget \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY . .

CMD ["python", "main.py"]
